TUM-live:
  "IT-Sec": "2021/W/it-sec:COMB"
  "NumProg": "2021/W/NumProg:COMB"

Username: "go42tum"
Password: "hunter2"

Keep-Original-File: true
Jumpcut: true

Output-Folder: "/app/output"

Maximum-Parallel-Downloads: 3
